version: '3.1'

services:
  mysql_db:
    image: mysql
    container_name: mysql_db_users
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_USER: ${NX_DB_USERNAME}
      MYSQL_PASSWORD: ${NX_DB_PASSWORD}
      MYSQL_DATABASE: ${NX_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${NX_DB_ROOT_PASSWORD}
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - ${NX_DB_PORT}:3306
